USE `reporting`;

DROP VIEW IF EXISTS `CRITICAL_WINWATCH`;
DROP VIEW IF EXISTS `CRITICAL_SERCHIO`;

CREATE VIEW `CRITICAL_WINWATCH` AS
SELECT
DATE(Data) DateOnly,
CONCAT_WS(' ',Evento,'PULSAR',RIGHT(Centrale,1),Messaggio) Critical,
SUM(contatore) tot
FROM `WINWATCH` WHERE
`Centrale` != 'UC' AND
`Evento` NOT REGEXP '(DISINSER|INSER|INIZIO|FINE|RISULTATO|ATTIVAZIONE)' AND
`Messaggio` NOT REGEXP '(RIPOSO|VISUAL|GEICO|ADMIN)'
GROUP BY DateOnly,Centrale,Evento,Messaggio
ORDER BY DateOnly DESC;

CREATE VIEW `CRITICAL_SERCHIO` AS
SELECT
DATE(Data) DateOnly,
CONCAT_WS(' ',evento,'PULSAR',centrale,Messaggio,COALESCE(seriale,''),COALESCE(Ospite,'')) Critical,
SUM(contatore) tot
FROM `SERCHIO` WHERE
`evento` NOT REGEXP '(TRANSITO EFFETTUATO|VARCO CHIUSO|VARCO NON APERTO|TASTIERA ABILITATA|ALLARMI ACQUISITI)'
GROUP BY DateOnly,centrale,evento,Messaggio
ORDER BY DateOnly DESC;

CREATE VIEW `CRITICAL` AS
SELECT * FROM CRITICAL_SERCHIO WHERE YEAR(DateOnly) = YEAR(CURDATE())
UNION
SELECT * FROM CRITICAL_WINWATCH WHERE YEAR(DateOnly) = YEAR(CURDATE())
ORDER BY DateOnly DESC;