DROP VIEW IF EXISTS `WINWATCH`;
DROP VIEW IF EXISTS `SERCHIO`;

CREATE VIEW `WINWATCH` AS
SELECT Centrale,Data,evento,messaggio,contatore FROM WIN_REPORT
LEFT JOIN WIN_EVENTI USING(id_evento)
LEFT JOIN WIN_MESSAGGI USING(id_messaggio)
ORDER BY Data DESC;

CREATE VIEW `SERCHIO` AS
SELECT Data,SER_REPORT.Centrale,seriale,evento,CONCAT(COALESCE(varco,''),' ',COALESCE(direzione,'')) AS Messaggio,nome AS Ospite,contatore 
FROM SER_REPORT
LEFT JOIN SER_TESSERE USING(id_tessera)
LEFT JOIN SER_EVENTI USING(id_evento)
LEFT JOIN SER_VARCHI USING(id_varco)
LEFT JOIN SER_OSPITI USING(id_ospite)
ORDER BY Data DESC;